/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    posts: Post;
    'vector-bulk-embeddings-runs': VectorBulkEmbeddingsRun;
    'vector-bulk-embedding-input-metadata': VectorBulkEmbeddingInputMetadatum;
    'vector-bulk-embeddings-batches': VectorBulkEmbeddingsBatch;
    default: Default;
    bulkDefault: BulkDefault;
    failingBulkDefault: FailingBulkDefault;
    'payload-kv': PayloadKv;
    users: User;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    posts: PostsSelect<false> | PostsSelect<true>;
    'vector-bulk-embeddings-runs': VectorBulkEmbeddingsRunsSelect<false> | VectorBulkEmbeddingsRunsSelect<true>;
    'vector-bulk-embedding-input-metadata': VectorBulkEmbeddingInputMetadataSelect<false> | VectorBulkEmbeddingInputMetadataSelect<true>;
    'vector-bulk-embeddings-batches': VectorBulkEmbeddingsBatchesSelect<false> | VectorBulkEmbeddingsBatchesSelect<true>;
    default: DefaultSelect<false> | DefaultSelect<true>;
    bulkDefault: BulkDefaultSelect<false> | BulkDefaultSelect<true>;
    failingBulkDefault: FailingBulkDefaultSelect<false> | FailingBulkDefaultSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      'payloadcms-vectorize:vectorize': TaskPayloadcmsVectorizeVectorize;
      'payloadcms-vectorize:prepare-bulk-embedding': TaskPayloadcmsVectorizePrepareBulkEmbedding;
      'payloadcms-vectorize:poll-or-complete-bulk-embedding': TaskPayloadcmsVectorizePollOrCompleteBulkEmbedding;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Bulk embedding run records. Created automatically when the Embed all action is triggered.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vector-bulk-embeddings-runs".
 */
export interface VectorBulkEmbeddingsRun {
  id: number;
  /**
   * Knowledge pool slug
   */
  pool: string;
  /**
   * Embedding version at submission time
   */
  embeddingVersion: string;
  status: 'queued' | 'running' | 'succeeded' | 'failed' | 'canceled';
  /**
   * Total number of batches in this run
   */
  totalBatches?: number | null;
  inputs?: number | null;
  succeeded?: number | null;
  failed?: number | null;
  /**
   * Timestamp when the batch was submitted
   */
  submittedAt?: string | null;
  /**
   * Timestamp when the batch finished
   */
  completedAt?: string | null;
  /**
   * Failure reason if the run ended in error
   */
  error?: string | null;
  /**
   * Data about chunks that failed during completion (collection, documentId, chunkIndex)
   */
  failedChunkData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Stores per-input metadata for bulk embedding runs.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vector-bulk-embedding-input-metadata".
 */
export interface VectorBulkEmbeddingInputMetadatum {
  id: number;
  /**
   * Bulk run this input belongs to
   */
  run: number | VectorBulkEmbeddingsRun;
  inputId: string;
  /**
   * Original chunk text
   */
  text: string;
  sourceCollection: string;
  docId: string;
  chunkIndex: number;
  embeddingVersion: string;
  /**
   * Extension field values for this chunk
   */
  extensionFields?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Individual batches within a bulk embedding run. Created when input count exceeds file limits.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vector-bulk-embeddings-batches".
 */
export interface VectorBulkEmbeddingsBatch {
  id: number;
  /**
   * Parent bulk embedding run
   */
  run: number | VectorBulkEmbeddingsRun;
  /**
   * Zero-based index of this batch within the run
   */
  batchIndex: number;
  /**
   * Provider-specific batch identifier
   */
  providerBatchId: string;
  status: 'queued' | 'running' | 'succeeded' | 'failed' | 'canceled';
  /**
   * Number of inputs in this batch
   */
  inputCount: number;
  /**
   * Number of successful embeddings
   */
  succeededCount?: number | null;
  /**
   * Number of failed embeddings
   */
  failedCount?: number | null;
  /**
   * Timestamp when the batch was submitted to provider
   */
  submittedAt?: string | null;
  /**
   * Timestamp when the batch finished
   */
  completedAt?: string | null;
  /**
   * Error message if the batch failed
   */
  error?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Vector embeddings for search and similarity queries. Created by the payloadcms-vectorize plugin. Embeddings cannot be added or modified, only deleted, through the admin panel. No other restrictions enforced.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "default".
 */
export interface Default {
  id: number;
  /**
   * The collection that this embedding belongs to
   */
  sourceCollection: string;
  /**
   * The ID of the source document
   */
  docId: string;
  /**
   * The index of this chunk
   */
  chunkIndex: number;
  /**
   * The original text that was vectorized
   */
  chunkText?: string | null;
  /**
   * The version of the embedding model used
   */
  embeddingVersion?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Vector embeddings for search and similarity queries. Created by the payloadcms-vectorize plugin. Embeddings cannot be added or modified, only deleted, through the admin panel. No other restrictions enforced.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bulkDefault".
 */
export interface BulkDefault {
  id: number;
  /**
   * The collection that this embedding belongs to
   */
  sourceCollection: string;
  /**
   * The ID of the source document
   */
  docId: string;
  /**
   * The index of this chunk
   */
  chunkIndex: number;
  /**
   * The original text that was vectorized
   */
  chunkText?: string | null;
  /**
   * The version of the embedding model used
   */
  embeddingVersion?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Vector embeddings for search and similarity queries. Created by the payloadcms-vectorize plugin. Embeddings cannot be added or modified, only deleted, through the admin panel. No other restrictions enforced.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "failingBulkDefault".
 */
export interface FailingBulkDefault {
  id: number;
  /**
   * The collection that this embedding belongs to
   */
  sourceCollection: string;
  /**
   * The ID of the source document
   */
  docId: string;
  /**
   * The index of this chunk
   */
  chunkIndex: number;
  /**
   * The original text that was vectorized
   */
  chunkText?: string | null;
  /**
   * The version of the embedding model used
   */
  embeddingVersion?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug:
          | 'inline'
          | 'payloadcms-vectorize:vectorize'
          | 'payloadcms-vectorize:prepare-bulk-embedding'
          | 'payloadcms-vectorize:poll-or-complete-bulk-embedding';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?:
    | (
        | 'inline'
        | 'payloadcms-vectorize:vectorize'
        | 'payloadcms-vectorize:prepare-bulk-embedding'
        | 'payloadcms-vectorize:poll-or-complete-bulk-embedding'
      )
    | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'vector-bulk-embeddings-runs';
        value: number | VectorBulkEmbeddingsRun;
      } | null)
    | ({
        relationTo: 'vector-bulk-embedding-input-metadata';
        value: number | VectorBulkEmbeddingInputMetadatum;
      } | null)
    | ({
        relationTo: 'vector-bulk-embeddings-batches';
        value: number | VectorBulkEmbeddingsBatch;
      } | null)
    | ({
        relationTo: 'default';
        value: number | Default;
      } | null)
    | ({
        relationTo: 'bulkDefault';
        value: number | BulkDefault;
      } | null)
    | ({
        relationTo: 'failingBulkDefault';
        value: number | FailingBulkDefault;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vector-bulk-embeddings-runs_select".
 */
export interface VectorBulkEmbeddingsRunsSelect<T extends boolean = true> {
  pool?: T;
  embeddingVersion?: T;
  status?: T;
  totalBatches?: T;
  inputs?: T;
  succeeded?: T;
  failed?: T;
  submittedAt?: T;
  completedAt?: T;
  error?: T;
  failedChunkData?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vector-bulk-embedding-input-metadata_select".
 */
export interface VectorBulkEmbeddingInputMetadataSelect<T extends boolean = true> {
  run?: T;
  inputId?: T;
  text?: T;
  sourceCollection?: T;
  docId?: T;
  chunkIndex?: T;
  embeddingVersion?: T;
  extensionFields?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vector-bulk-embeddings-batches_select".
 */
export interface VectorBulkEmbeddingsBatchesSelect<T extends boolean = true> {
  run?: T;
  batchIndex?: T;
  providerBatchId?: T;
  status?: T;
  inputCount?: T;
  succeededCount?: T;
  failedCount?: T;
  submittedAt?: T;
  completedAt?: T;
  error?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "default_select".
 */
export interface DefaultSelect<T extends boolean = true> {
  sourceCollection?: T;
  docId?: T;
  chunkIndex?: T;
  chunkText?: T;
  embeddingVersion?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bulkDefault_select".
 */
export interface BulkDefaultSelect<T extends boolean = true> {
  sourceCollection?: T;
  docId?: T;
  chunkIndex?: T;
  chunkText?: T;
  embeddingVersion?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "failingBulkDefault_select".
 */
export interface FailingBulkDefaultSelect<T extends boolean = true> {
  sourceCollection?: T;
  docId?: T;
  chunkIndex?: T;
  chunkText?: T;
  embeddingVersion?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskPayloadcms-vectorize:vectorize".
 */
export interface TaskPayloadcmsVectorizeVectorize {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskPayloadcms-vectorize:prepare-bulk-embedding".
 */
export interface TaskPayloadcmsVectorizePrepareBulkEmbedding {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskPayloadcms-vectorize:poll-or-complete-bulk-embedding".
 */
export interface TaskPayloadcmsVectorizePollOrCompleteBulkEmbedding {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}